### ISSUE TITLE
Bug during resetting fg/bg on windows.

### ISSUE THREAD

**Issue by kingseva** [agauniyal/rang#66] opened 2017-10-31 07:54 UTC
I'm look into your test colortest.cpp and run it on windows7 on mingw64 6.3.0. It does not work properly.

Look at your test code:

```c++
	// Visual test for background colors
	std::cout 
	  << rang::control::forceColor << rang::bg::green
	  << "This text has green background." << rang::bg::reset << std::endl
	  << rang::bg::red << "This text has red background." << rang::bg::reset
	  << std::endl
```
...

```c++
	  // Visual test for foreground colors
	  << rang::fg::green << "This text has green color." << rang::fg::reset
	  << std::endl
	  << rang::fg::red << "This text has red color." << rang::fg::reset
	  << std::endl
```
When you doing rang::fg::reset or rang::bg::reset you pass 39-30 = 9 and 49-40 = 9 to your funcion:

```c++
	inline WORD reverseRGB(WORD rgb)
	{
		static const WORD rev[8] = { 0, 4, 2, 6, 1, 5, 3, 7 };
		return rev[rgb];
	}
```
and it returns some trash instead of correct 3 bit value. 
I'm change your functions to workaround this:

```c++
	inline void setWinAttribute(rang::bg col, WORD &state)
	{
		state &= 0xFF0F;
		if(col != rang::bg::reset)
			state |= reverseRGB(static_cast<WORD>(col) - 40) << 4;
	}

	inline void setWinAttribute(rang::fg col, WORD &state)
	{
		state &= 0xFFF0;
		if(col != rang::fg::reset)
			state |= reverseRGB(static_cast<WORD>(col) - 30);
		else
			state |= (FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_RED);
	}
```
And it's fixed.

So. Default windows state is **7** (FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_RED) for foreground color and **0** for background color **at most** cases.  
By the way you can store user default settings from `GetConsoleScreenBufferInfo` something like this:

```c++
            static WORD defaultAttributes = 0;
            if (!defaultAttributes)
            {
                CONSOLE_SCREEN_BUFFER_INFO info;
                if (!GetConsoleScreenBufferInfo(getConsoleHandle(), &info))
                    return;
                defaultAttributes = info.wAttributes;
            }
```
and than use fg/bg color bits from that variable instead of 7 and 0.

**Comment by agauniyal** [comment] 2017-10-31 13:03
@kingseva thankyou for raising the issue. I use Linux primarily since about 3-4 years and windows 10 onwards both Linux and windows use ANSI escape sequences correctly so it is supported. Another user provided windows (< 10) support which I'm thankful for but it might be possible that some error sneaked in during PRs so this does not work as intended on MinGW.

Would you mind opening another PR against the [next-release](https://github.com/agauniyal/rang/tree/next-release) branch to fix this issue so I can credit you on next release? This time I'm going to refactor code a bit and will make sure to test on all platforms I can get my hands on 😄

**Comment by agauniyal** [comment] 2017-11-07 12:37
Merged! Thankyou for your work on this PR @kingseva 😄

**Closed by agauniyal** 2017-11-07 12:37 UTC
